namespace grafxkid_charSprites {
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ggirl11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ggirl12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ggirl13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ggirl14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ggirl21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ggirl22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ggirl23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ggirl24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge31 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge32 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge33 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Ge34 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy301 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy302 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy303 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy304 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy305 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy306 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy307 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy308 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy309 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gboy310 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gceralt1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gceralt2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gceralt3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gceralt4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gceralt5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gceralt6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gceralt7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gceralt8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gjs1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gjs2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gjs3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gjs4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gjs5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gjs6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gjs7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const Gjs8 = image.ofBuffer(hex``);

}
